# Generated by Django 5.1 on 2024-08-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('mail', models.CharField(max_length=255, verbose_name='correo')),
                ('group', models.CharField(max_length=255, verbose_name='grupo')),
            ],
        ),
    ]
